/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Fridge | Ready")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="t013",targetState="check",cond=whenDispatch("check_food"))
					transition(edgeName="t014",targetState="exposestate",cond=whenDispatch("fridgestate"))
				}	 
				state("check") { //this:State
					action { //it:State
						updateResourceRep( "checkfood"  
						)
						println("Fridge | Requirement: CHECK food presence")
						delay(500) 
						if( checkMsgContent( Term.createTerm("check_food(Foodcode)"), Term.createTerm("check_food(pizza)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("food_available", "food_available(pizza)" ,"robot" ) 
						}
						if( checkMsgContent( Term.createTerm("check_food(Foodcode)"), Term.createTerm("check_food(pasta)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								forward("food_not_available", "food_not_available(pasta)" ,"robot" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("exposestate") { //this:State
					action { //it:State
						updateResourceRep( "exposestate"  
						)
						println("Fridge | Requirement: EXPOSE FRIDGE STATE")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
