/* Generated by AN DISI Unibo */ 
package it.unibo.robot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Butler | Ready")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
					}
					 transition(edgeName="to0",targetState="handleprepare",cond=whenDispatch("prepare"))
					transition(edgeName="to1",targetState="handleadd",cond=whenDispatch("add"))
					transition(edgeName="to2",targetState="handleclear",cond=whenDispatch("clear"))
					transition(edgeName="to3",targetState="handlestop",cond=whenDispatch("stop"))
					transition(edgeName="to4",targetState="handleexpose",cond=whenDispatch("expose"))
				}	 
				state("handleexpose") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("expose(Cmd)"), Term.createTerm("expose(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler | EXPOSE started")
								updateResourceRep( "handlingexpose"  
								)
								forward("expose", "expose(${payloadArg(0)})" ,"robotexecutor" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("handleprepare") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("prepare(Cmd)"), Term.createTerm("prepare(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler | PREPARE started")
								updateResourceRep( "handlingprepare"  
								)
								forward("prepare", "prepare(${payloadArg(0)})" ,"robotexecutor" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("handleadd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("add(Foodcode,Quantity)"), Term.createTerm("add(Foodcode,Quantity)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler | ADD started")
								updateResourceRep( "handlingadd"  
								)
								forward("add", "add(${payloadArg(0)},${payloadArg(1)})" ,"robotexecutor" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("handleclear") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("clear(Cmd)"), Term.createTerm("clear(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("Butler | CLEAR started")
								updateResourceRep( "handlingclear"  
								)
								forward("clear", "clear(${payloadArg(0)})" ,"robotexecutor" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("handlestop") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("stop(Cmd)"), Term.createTerm("stop(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "stopped"  
								)
								println("Butler |  STOP action")
								forward("stop", "stop(${payloadArg(0)})" ,"robotmover" ) 
						}
					}
					 transition(edgeName="t05",targetState="handlereactivate",cond=whenDispatch("reactivate"))
				}	 
				state("handlereactivate") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("reactivate(Cmd)"), Term.createTerm("reactivate(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "reactivated"  
								)
								println("Butler |  CONTINUE action")
								forward("reactivate", "reactivate(${payloadArg(0)})" ,"robotmover" ) 
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
