/* Generated by AN DISI Unibo */ 
package it.unibo.robotexecutor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotexecutor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('preparerequirements.pl')","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						updateResourceRep( "athome"  
						)
					}
					 transition(edgeName="t06",targetState="handleprepare",cond=whenDispatch("prepare"))
				}	 
				state("handleprepare") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("prepare(Cmd)"), Term.createTerm("prepare(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "startprepare"  
								)
								println("Robot executor | Prepare: start")
								request("goto", "goto(pantry)" ,"robotmover" )  
						}
					}
					 transition(edgeName="t17",targetState="atpantry",cond=whenReply("arrivedat"))
				}	 
				state("atpantry") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("arrivedat(Destination)"), Term.createTerm("arrivedat(pantry)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "atpantry"  
								)
								println("Robot executor | Prepare: dishes taken")
								request("goto", "goto(table)" ,"robotmover" )  
						}
					}
					 transition(edgeName="t28",targetState="attable_dishes",cond=whenReply("arrivedat"))
				}	 
				state("attable_dishes") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("arrivedat(Destination)"), Term.createTerm("arrivedat(table)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "attable_dishes"  
								)
								println("Robot executor | Prepare: dishes on table ")
								request("goto", "goto(fridge)" ,"robotmover" )  
						}
					}
					 transition(edgeName="t39",targetState="atfridge",cond=whenReply("arrivedat"))
				}	 
				state("atfridge") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("arrivedat(Destination)"), Term.createTerm("arrivedat(fridge)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "atfridge"  
								)
								solve("food(F)","") //set resVar	
								forward("take_foodlist", "take_foodlist(${getCurSol("F")})" ,"fridge" ) 
								println("Robot executor | Prepare: food taken")
								request("goto", "goto(table)" ,"robotmover" )  
						}
					}
					 transition(edgeName="t510",targetState="attable_food",cond=whenReply("arrivedat"))
				}	 
				state("attable_food") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("arrivedat(Destination)"), Term.createTerm("arrivedat(table)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "attable_food"  
								)
								println("Robot executor | Prepare: food on table")
								request("goto", "goto(home)" ,"robotmover" )  
						}
					}
					 transition(edgeName="t611",targetState="endPrepare",cond=whenReply("arrivedat"))
				}	 
				state("endPrepare") { //this:State
					action { //it:State
						updateResourceRep( "endprepare"  
						)
						println("Robot executor | Prepare: end")
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
